resource_group_name         = "basic-example-resource-group"
location                    = "West Europe"
function_app_name           = "myappsacc4657"
storage_account_name        = "stoaccsacc67895"
app_service_plan_name       = "basic-app-linux-plan"
function_worker_runtime     = "dotnet-isolated"
subscription_id             = "03eb6bc9-fcb2-4ebf-9b15-417f8df89fee"